[package]
name = "rptadv-product"
build = "build.rs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rpt-advanced-core = { path = "../core" }
rtrb = "0.3.2"
ureq = { version = "2.12", default-features = false, features = ["tls"] }
url = "2.5"

[dev-dependencies]
rptadv-file-adapter = { path = "../file-adapter" }
rptadv-speech-adapter = { path = "../speech-adapter" }
rptadv-control-standalone-adapter = { path = "../control-standalone-adapter" }

[build-dependencies]
bindgen = "0.72.1"
