[package]
name = "rpt-advanced-standalone"
build = "build.rs"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "rpt-advanced"
path = "src/main.rs"

[dependencies]
crossbeam-queue = "0.3.12"
libc = "0.2"
libloading = "0.8"
rpt-advanced-core = { path = "../core" }
serde_json = "1"
ureq = { version = "2.12", default-features = false, features = ["tls"] }

[build-dependencies]
bindgen = "0.72.1"
